from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt
import io
from datetime import datetime

DARK_BLUE = RGBColor(0x0D, 0x1B, 0x2A)
MID_BLUE = RGBColor(0x1B, 0x4F, 0x72)
ACCENT = RGBColor(0x27, 0xAE, 0x60)
RED_ACCENT = RGBColor(0xC0, 0x39, 0x2B)
LIGHT_GRAY = RGBColor(0xF4, 0xF6, 0xF7)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
TEXT_DARK = RGBColor(0x1A, 0x1A, 0x2E)
MUTED = RGBColor(0x7F, 0x8C, 0x8D)

def _add_text(tf, text, size=12, bold=False, color=None, align=PP_ALIGN.LEFT):
    tf.word_wrap = True
    para = tf.paragraphs[0]
    para.alignment = align
    run = para.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color or TEXT_DARK

def _fill_shape(shape, color):
    shape.fill.solid()
    shape.fill.fore_color.rgb = color

def _set_line_none(shape):
    shape.line.fill.background()

def add_slide_title(prs, title, subtitle=""):
    slide_layout = prs.slide_layouts[6]
    slide = prs.slides.add_slide(slide_layout)
    bg = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
    _fill_shape(bg, DARK_BLUE)
    _set_line_none(bg)

    accent_bar = slide.shapes.add_shape(1, Inches(0), Inches(3.8), prs.slide_width, Pt(3))
    _fill_shape(accent_bar, ACCENT)
    _set_line_none(accent_bar)

    txBox = slide.shapes.add_textbox(Inches(0.8), Inches(2.2), Inches(8), Inches(1.2))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.LEFT
    run = p.add_run()
    run.text = title
    run.font.size = Pt(36)
    run.font.bold = True
    run.font.color.rgb = WHITE

    if subtitle:
        txBox2 = slide.shapes.add_textbox(Inches(0.8), Inches(3.5), Inches(8), Inches(0.6))
        tf2 = txBox2.text_frame
        p2 = tf2.paragraphs[0]
        run2 = p2.add_run()
        run2.text = subtitle
        run2.font.size = Pt(14)
        run2.font.color.rgb = RGBColor(0xAE, 0xD6, 0xF1)

    date_box = slide.shapes.add_textbox(Inches(0.8), Inches(6.6), Inches(8), Inches(0.4))
    tf3 = date_box.text_frame
    p3 = tf3.paragraphs[0]
    run3 = p3.add_run()
    run3.text = f"Generated by FinSight AI  ·  {datetime.now().strftime('%B %d, %Y')}"
    run3.font.size = Pt(10)
    run3.font.color.rgb = MUTED

    return slide

def add_section_header(prs, title):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
    _fill_shape(bg, MID_BLUE)
    _set_line_none(bg)
    bar = slide.shapes.add_shape(1, Inches(0), Inches(3.5), Inches(0.12), Inches(1.0))
    _fill_shape(bar, ACCENT)
    _set_line_none(bar)
    txBox = slide.shapes.add_textbox(Inches(0.5), Inches(3.2), Inches(9), Inches(1.2))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = title
    run.font.size = Pt(28)
    run.font.bold = True
    run.font.color.rgb = WHITE
    return slide

def _content_slide(prs, title):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.shapes.add_shape(1, 0, 0, prs.slide_width, prs.slide_height)
    _fill_shape(bg, WHITE)
    _set_line_none(bg)
    header_bar = slide.shapes.add_shape(1, 0, 0, prs.slide_width, Inches(0.9))
    _fill_shape(header_bar, DARK_BLUE)
    _set_line_none(header_bar)
    txBox = slide.shapes.add_textbox(Inches(0.4), Inches(0.15), Inches(9), Inches(0.6))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = title
    run.font.size = Pt(16)
    run.font.bold = True
    run.font.color.rgb = WHITE
    return slide

def add_kpi_slide(prs, metrics):
    slide = _content_slide(prs, "Key Performance Indicators")
    summary = metrics.get("summary", {})
    account_totals = metrics.get("account_totals", [])

    kpis = []
    revenue_accounts = [r for r in account_totals if "revenue" in str(r.get("account", "")).lower() or "revenue" in str(r.get("category", "")).lower()]
    cogs_accounts = [r for r in account_totals if "cost of goods" in str(r.get("account", "")).lower() or "cogs" in str(r.get("category", "")).lower()]
    gp_accounts = [r for r in account_totals if "gross profit" in str(r.get("account", "")).lower()]
    ebitda_accounts = [r for r in account_totals if "ebitda" in str(r.get("account", "")).lower()]

    def sum_actual(rows): return sum(r.get("actual", 0) for r in rows)
    def sum_budget(rows): return sum(r.get("budget", 0) for r in rows)

    if revenue_accounts:
        act = sum_actual(revenue_accounts)
        bud = sum_budget(revenue_accounts)
        var = act - bud
        kpis.append(("Net Revenue", f"${act/1e6:.1f}M", f"${var/1e6:+.1f}M vs Budget", var >= 0))
    if cogs_accounts:
        act = sum_actual(cogs_accounts)
        bud = sum_budget(cogs_accounts)
        var = act - bud
        kpis.append(("COGS", f"${act/1e6:.1f}M", f"${var/1e6:+.1f}M vs Budget", var <= 0))
    if gp_accounts:
        act = sum_actual(gp_accounts)
        bud = sum_budget(gp_accounts)
        var = act - bud
        kpis.append(("Gross Profit", f"${act/1e6:.1f}M", f"${var/1e6:+.1f}M vs Budget", var >= 0))
    if ebitda_accounts:
        act = sum_actual(ebitda_accounts)
        bud = sum_budget(ebitda_accounts)
        var = act - bud
        kpis.append(("EBITDA", f"${act/1e6:.1f}M", f"${var/1e6:+.1f}M vs Budget", var >= 0))

    if not kpis:
        kpis = [("Total Actual", f"${summary.get('total_actual', 0)/1e6:.1f}M",
                 f"${(summary.get('total_variance_vs_budget') or 0)/1e6:+.1f}M vs Budget",
                 (summary.get('total_variance_vs_budget') or 0) >= 0)]

    card_w = Inches(2.1)
    card_h = Inches(1.6)
    card_y = Inches(1.4)
    spacing = Inches(0.18)
    total_w = len(kpis) * card_w + (len(kpis) - 1) * spacing
    start_x = (prs.slide_width - total_w) / 2

    for i, (label, value, variance, favorable) in enumerate(kpis):
        x = start_x + i * (card_w + spacing)
        card = slide.shapes.add_shape(1, x, card_y, card_w, card_h)
        _fill_shape(card, LIGHT_GRAY)
        _set_line_none(card)

        accent = slide.shapes.add_shape(1, x, card_y, card_w, Pt(4))
        _fill_shape(accent, ACCENT if favorable else RED_ACCENT)
        _set_line_none(accent)

        lbl = slide.shapes.add_textbox(x + Inches(0.1), card_y + Inches(0.12), card_w - Inches(0.2), Inches(0.3))
        tf = lbl.text_frame
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = label
        run.font.size = Pt(10)
        run.font.color.rgb = MUTED

        val_box = slide.shapes.add_textbox(x + Inches(0.1), card_y + Inches(0.42), card_w - Inches(0.2), Inches(0.55))
        tf2 = val_box.text_frame
        p2 = tf2.paragraphs[0]
        run2 = p2.add_run()
        run2.text = value
        run2.font.size = Pt(22)
        run2.font.bold = True
        run2.font.color.rgb = TEXT_DARK

        var_box = slide.shapes.add_textbox(x + Inches(0.1), card_y + Inches(1.05), card_w - Inches(0.2), Inches(0.35))
        tf3 = var_box.text_frame
        p3 = tf3.paragraphs[0]
        run3 = p3.add_run()
        run3.text = variance
        run3.font.size = Pt(10)
        run3.font.color.rgb = ACCENT if favorable else RED_ACCENT

    return slide

def add_variance_table_slide(prs, metrics):
    slide = _content_slide(prs, "Budget vs. Actuals — Variance Analysis")
    rows = metrics.get("account_totals", [])
    if not rows:
        return slide

    has_budget = any(r.get("budget") for r in rows)
    has_prior = any(r.get("prior_period") for r in rows)

    headers = ["Account", "Actual", "Budget", "Var $", "Var %"] if has_budget else ["Account", "Actual", "Prior Period", "Var $", "Var %"]
    col_widths = [Inches(2.8), Inches(1.4), Inches(1.4), Inches(1.3), Inches(1.1)]

    table_top = Inches(1.1)
    table_left = Inches(0.3)
    table_h = Inches(5.0)
    table_w = sum(col_widths)

    display_rows = rows[:12]
    tbl = slide.shapes.add_table(len(display_rows) + 1, len(headers), table_left, table_top, int(table_w), int(table_h)).table

    for col_idx, (header, width) in enumerate(zip(headers, col_widths)):
        tbl.columns[col_idx].width = int(width)
        cell = tbl.cell(0, col_idx)
        cell.text = header
        cell.fill.solid()
        cell.fill.fore_color.rgb = DARK_BLUE
        para = cell.text_frame.paragraphs[0]
        run = para.add_run() if not para.runs else para.runs[0]
        if para.runs:
            para.runs[0].font.size = Pt(10)
            para.runs[0].font.bold = True
            para.runs[0].font.color.rgb = WHITE
        para.alignment = PP_ALIGN.CENTER

    for row_idx, row in enumerate(display_rows):
        actual = row.get("actual", 0)
        budget = row.get("budget", 0) if has_budget else row.get("prior_period", 0)
        var = row.get("variance_vs_budget", row.get("variance_vs_prior", 0))
        var_pct = row.get("variance_pct_budget", row.get("variance_pct_prior", 0))
        account_name = row.get("account", row.get("category", "N/A"))

        values = [
            account_name,
            f"${actual:,.0f}",
            f"${budget:,.0f}",
            f"${var:+,.0f}",
            f"{var_pct:+.1f}%",
        ]

        fill_color = WHITE if row_idx % 2 == 0 else LIGHT_GRAY

        for col_idx, val in enumerate(values):
            cell = tbl.cell(row_idx + 1, col_idx)
            cell.text = val
            cell.fill.solid()
            cell.fill.fore_color.rgb = fill_color
            para = cell.text_frame.paragraphs[0]
            if para.runs:
                para.runs[0].font.size = Pt(9)
                para.runs[0].font.color.rgb = TEXT_DARK
                if col_idx in (3, 4) and var != 0:
                    para.runs[0].font.color.rgb = ACCENT if var >= 0 else RED_ACCENT
            para.alignment = PP_ALIGN.RIGHT if col_idx > 0 else PP_ALIGN.LEFT

    return slide

def add_commentary_slide(prs, commentary: str, title: str = "Executive Commentary & Management Actions"):
    slide = _content_slide(prs, title)
    txBox = slide.shapes.add_textbox(Inches(0.4), Inches(1.05), Inches(9.2), Inches(5.8))
    tf = txBox.text_frame
    tf.word_wrap = True
    tf.auto_size = None

    paragraphs = [p.strip() for p in commentary.split("\n") if p.strip()]
    for i, para_text in enumerate(paragraphs[:10]):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.space_before = Pt(6)
        run = p.add_run()
        run.text = para_text
        is_header = para_text.endswith(":") or para_text.isupper() or para_text.startswith("**")
        run.font.size = Pt(11) if is_header else Pt(10)
        run.font.bold = is_header
        run.font.color.rgb = MID_BLUE if is_header else TEXT_DARK

    return slide

def generate_pptx(metrics: dict, commentary: str, filename: str = "Dataset") -> bytes:
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)

    add_slide_title(prs, "FinSight AI", f"Management Reporting Pack  ·  {filename}")
    add_kpi_slide(prs, metrics)
    add_variance_table_slide(prs, metrics)
    add_commentary_slide(prs, commentary, "Executive Summary & Key Insights")
    add_section_header(prs, "Powered by FinSight AI")

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf.read()
